import{a as P,S,i}from"./assets/vendor-rOMtvQ2t.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&d(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function d(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const v="50866532-7da9a026719ecf3bca8b50bdf",E="https://pixabay.com/api/",R=15;async function u(o,t){return(await P.get(E,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:R}})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".load-more"),q=new S(".gallery a");function y(o){const t=o.map(r=>`
    <li class="gallery-item">
      <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${r.likes}</p>
        <p><b>Views:</b> ${r.views}</p>
        <p><b>Comments:</b> ${r.comments}</p>
        <p><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",t),q.refresh()}function M(){f.innerHTML=""}function p(){h.classList.remove("hidden")}function g(){h.classList.add("hidden")}function b(){m.classList.remove("hidden")}function l(){m.classList.add("hidden")}const L=document.querySelector(".form"),$=L.querySelector('input[name="search-text"]'),B=document.querySelector(".load-more");let n=1,a="";const w=15;L.addEventListener("submit",async o=>{if(o.preventDefault(),a=$.value.trim(),!!a){n=1,M(),l(),p();try{const t=await u(a,n);if(!t.hits.length)i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"});else{y(t.hits);const r=Math.ceil(t.totalHits/w);n>=r?(l(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"})):b()}}catch{i.error({message:"Something went wrong. Please try again later.",position:"bottomRight"})}finally{g()}}});B.addEventListener("click",async()=>{n+=1,p(),l();try{const o=await u(a,n);y(o.hits);const t=Math.ceil(o.totalHits/w);n>=t?i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}):b(),A()}catch{i.error({message:"Something went wrong. Please try again later.",position:"bottomRight"})}finally{g()}});function A(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
